kamerbusinesscenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
urlpatterns = [
    path('sellerCenter/',include('sellerCenter.urls')),
    path('shop/',include('shop.urls', namespace = 'shop')),
    path('admin/',admin.site.urls  ),
    path('',RedirectView.as_view(url='sellerCenter/' )),
    
]

sellerCenter/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from .forms import RegistrationForm

app_name = 'sellerCenter'

urlpatterns = [
   # path('', RedirectView.as_view(url='dashboard')),
    
    path('', RedirectView.as_view(url='dashboard')),
    path('dashboard', views.index, name = "dashboard"),
    path('users', views.users, name = "users"),
    path('products', views.products, name = "products"),
    path('orders', views.orders, name = "orders"),
    path('orders/export', views.export_orders, name = "orders.export"),
    path('login', auth_views.LoginView.as_view(), name = "login"),
    path('user', views.createUser, name = "user.create"),
    path('user/update/<int:user_id>', views.updateUser, name = "user.update"),
    path('user/form-update/<int:user_id>', views.form_updateUser, name = "user.form.update"),
    path('user/delete/<int:user_id>', views.deleteUser, name = "user.delete"),
    path('user/form-delete/<int:user_id>', views.form_deleteUser, name = "user.form.delete"),
    path('user/root/create', views.createsuperuser, name = "user.create.root"),
    path('product', views.createProduct, name = "product.create"),
    path('product/<str:sku>', views.createProduct, name = "product.view.shop"),
    path('product/update/<str:sku>', views.updateProduct, name = "product.update"),
    path('product/form-update/<str:sku>', views.form_updateProduct, name = "product.form.update"),
    path('product/delete/<str:sku>', views.deleteProduct, name = "product.delete"),
    path('product/form-delete/<str:sku>', views.form_deleteProduct, name = "product.form.delete"),
    path('seller/<str:sku>/referal', views.get_referal_link, name = "seller.product.referal"),

    path('order/<str:id>/details', views.detailsOrder, name = 'order.details'),
    path('order/<str:id>/invoice', views.generateInvoice, name ='order.invoice'),

    path('delivery_fees', views.deliveryFees, name = 'delivery_fees'),
    path('delivery_fee/create', views.createDeliveryFee, name = 'delivery_fee.create'),
    path('delivery_fee/<str:sku>/<str:city_id>', views.getDeliveryFee, name = 'delivery_fee.product.city'),
    
    path('cities', views.cities, name = 'cities'),
    path('city/create', views.createCity, name = 'city.create'),
]

shop/urls.py
from django.urls import path, include
from . import views
from django.views.generic import RedirectView

app_name = 'shop'

urlpatterns = [
   # path('', RedirectView.as_view(url='dashboard')),
    
    path('', RedirectView.as_view(url='dashboard')),
    path('product/<str:referal_id>', views.shop, name = "product.view.shop"),
    path('product/<str:referal_id>/order', views.makeOrder, name = "make.order"),
    path('thanks', views.thanks, name = "thanks"),

]

sellerCenter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from .generator import generate_id
from django.db.models.query import QuerySet
from django.utils import timezone
import barcode
from barcode.writer import ImageWriter
from django.core.files.base import ContentFile
from io import BytesIO
# Create your models here.

class SoftDeletionQuerySet(QuerySet):
    def delete(self):
        return super(SoftDeletionQuerySet, self).update(deleted_at=timezone.now())

    def hard_delete(self):
        return super(SoftDeletionQuerySet, self).delete()

    def alive(self):
        return self.filter(deleted_at=None)

    def dead(self):
        return self.exclude(deleted_at=None)

class SoftDeletionManager(models.Manager):
    def __init__(self, *args, **kwargs):
        self.alive_only = kwargs.pop('alive_only', True)
        super(SoftDeletionManager, self).__init__(*args, **kwargs)

    def get_queryset(self):
        if self.alive_only:
            return SoftDeletionQuerySet(self.model).filter(deleted_at=None)
        return SoftDeletionQuerySet(self.model)

    def hard_delete(self):
        return self.get_queryset().hard_delete()

class SoftDeletionModel(models.Model):
    deleted_at = models.DateField(blank=True, null=True)

    objects = SoftDeletionManager()
    all_objects = SoftDeletionManager(alive_only=False)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def hard_delete(self):
        super(SoftDeletionModel, self).delete()

class City(SoftDeletionModel):
    city_id = models.CharField(db_column='CITY_ID', primary_key=True, max_length=255)  # Field name made lowercase.
    name = models.CharField(db_column='NAME', max_length=255)  # Field name made lowercase.
    code = models.CharField(db_column='CODE', max_length=128)  # Field name made lowercase.
    created_at = models.DateField(db_column='CREATED_AT', auto_now_add=True)  # Field name made lowercase.


    def set_id(self):
        self.city_id = generate_id('sellerCenter','City','city_id', self.name)

    def __str__(self):
        return self.code

class Product(SoftDeletionModel):
    name = models.CharField(max_length=200)
    description = models.TextField(null = True)
    promo_price = models.PositiveIntegerField(default = 0)
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to = 'sellerCenter/product_image/%y/%m/%d')
    sku = models.CharField(max_length=200, primary_key=True)
    barcode = models.ImageField(upload_to = 'sellerCenter/barecode/%y/%m/%d', null = True, blank = True)
    action = models.ManyToManyField(
        User,
        through = 'ProductManagement',
        related_name = 'product'
        
    )

    created_at = models.DateField(auto_now_add = True)
    updated_at = models.DateField(auto_now = True)
    def get_absolute_url(self):
        return 'http://kamerbusinesscenter.com'+ reverse('shop:product.view.shop', args = [self.sku])

    def set_id(self):
        self.sku = generate_id('sellerCenter','Product','sku', self.name)
        code39 = barcode.get('code39', self.sku, writer = ImageWriter())
        code39_img = code39.render()
        image_io = BytesIO()
        code39_img.save(image_io, format='PNG')
        image_name = 'barcode-'+self.sku
        self.barcode.save(image_name, content=ContentFile(image_io.getvalue()), save=False)
        
    def __str__(self):
        return self.name

    delivery_fee = models.ManyToManyField(
        City,
        through='DeliveryFee',
        related_name='delivery_fee'

    )
class Referal(models.Model):
    referal_id = models.CharField(db_column='REFERAL_ID', primary_key=True, max_length=255)  # Field name made lowercase.
    product = models.ForeignKey(Product, models.DO_NOTHING, db_column='SKU')  # Field name made lowercase.
    seller = models.ForeignKey(User, models.DO_NOTHING, db_column='USER_ID')  # Field name made lowercase.
    link = models.CharField(db_column='LINK', max_length=255, null = True)  # Field name made lowercase.
    is_active = models.BooleanField(db_column='IS_ACTIVE', default = True)  # Field name made lowercase.
    
    class Meta:
        db_table = 'referal'

    def set_link(self):
        self.link = 'http://kamerbusinesscenter.com'+ reverse('shop:product.view.shop', args = [self.referal_id])
    
    def set_id(self):
        self.referal_id = generate_id('sellerCenter','Referal','referal_id', 'Referal')

class Order(SoftDeletionModel):
    customer_firstName = models.CharField(max_length=200)
    customer_lastName = models.CharField(max_length=200)
    customer_phone = models.CharField(max_length=200)
    customer_email = models.EmailField()
    total_price = models.PositiveIntegerField()
    delivery_fee = models.PositiveIntegerField(default = 0)
    delivery_address = models.CharField(max_length=200, null = True)
    order_number = models.CharField(max_length=200, primary_key=True)
    status = models.CharField(max_length=200, default="Complet")
    payment_status = models.CharField(max_length=200, default="En attente")
    barcode = models.ImageField(upload_to = 'sellerCenter/barecode/%y/%m/%d', null = True, blank = True)
    referal = models.ForeignKey(Referal, models.DO_NOTHING, db_column='REFERAL_ID', null = True)  # Field name made lowercase.
    products = models.ManyToManyField(
        Product,
        through = 'OrderProduct',
        related_name = 'order'
    )
    action = models.ManyToManyField(
        User,
        through = 'OrderManagement',
        related_name = 'order'
    )
    created_at = models.DateField(auto_now_add = True)
    updated_at = models.DateField(auto_now = True)

    def set_id(self):
        self.order_number = generate_id('sellerCenter','Order','order_number', 'ORDER')
        code39 = barcode.get('code39', self.order_number, writer = ImageWriter())
        code39_img = code39.render()
        image_io = BytesIO()
        code39_img.save(image_io, format='PNG')
        image_name = 'barcode-'+self.order_number
        self.barcode.save(image_name, content=ContentFile(image_io.getvalue()), save=False)

class DeliveryFee(SoftDeletionModel):
    city = models.ForeignKey(City, models.DO_NOTHING, db_column='CITY_ID')  # Field name made lowercase.
    sku = models.ForeignKey(Product, models.DO_NOTHING, db_column='SKU')  # Field name made lowercase.
    amount = models.PositiveIntegerField(db_column='AMOUNT', default = 1500)  # Field name made lowercase.
    created_at = models.DateField(db_column='CREATED_AT', auto_now_add=True)  # Field name made lowercase.
   
class OrderProduct(SoftDeletionModel):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    created_at = models.DateField(auto_now_add = True)
    updated_at = models.DateField(auto_now = True)

class ProductManagement(SoftDeletionModel):
    action =  models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add = True)
    updated_at = models.DateField(auto_now = True)
    product = models.ForeignKey(Product, on_delete = models.CASCADE, null = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)

class OrderManagement(SoftDeletionModel):
    action =  models.CharField(max_length=200)
    reason =  models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add = True)
    updated_at = models.DateField(auto_now = True)
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

sellerCenter/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Product, DeliveryFee, City

class RegistrationForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username','email','last_name','first_name','password')
		#fields.widget.attrs.update({'class' : 'form-control'})

		widgets = { 
            'username': forms.TextInput(attrs={'class': 'form-control','id': 'username','placeholder': 'User Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control','id': 'inputEmail','placeholder': 'Email'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control','id': 'last_name','placeholder': 'Last Name'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control','id': 'first_name','placeholder': 'First Name'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control','id': 'password','placeholder': 'Password'}),
        }
class updateUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('email','last_name','first_name')
		#fields.widget.attrs.update({'class' : 'form-control'})

		widgets = { 
            'email': forms.EmailInput(attrs={'class': 'form-control','id': 'inputEmail','placeholder': 'Email'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control','id': 'last_name','placeholder': 'Last Name'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control','id': 'first_name','placeholder': 'First Name'}),
        }

class createProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ('name','description','promo_price','price','image')

		widgets = { 
            'name': forms.TextInput(attrs={'class': 'form-control','id': 'name','placeholder': 'Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'promo_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }
class updateProductForm(forms.ModelForm):
    image = forms.FileField(required = False, widget = forms.FileInput)
    class Meta:
        model = Product
        fields = ('name','description','promo_price','price','image')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','id': 'name','placeholder': 'Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'promo_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

class deliveryFeeForm(forms.ModelForm):
   
    class Meta:
        model = DeliveryFee
        fields = ('amount', 'sku', 'city')
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Amount'}),
            'sku': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
        }

class CreateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ('name', 'code')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Name'}),
            'code': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Code'}),
        }

sellerCenter/templates/sellerCenter/order/details.html
<!-- Modal -->
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{_("Details de la Commande No")}}: {{order.order_number}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        <div class="modal-body">
            <div class="list-group">
               
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start disabled">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{_("Information du client")}}</h5>
                    </div>
                    
                    <table class="mx-auto  table-inverse table-responsive" style="border:none">
                    
                        
                            <tr>
                                <td scope="row"></td>
                                <td >{{_("Nom Complet")}}: </td>
                                <td >{{order.customer_firstName}} {{order.customer_lastName}}</td>
                            </tr>
                            <tr>
                                <td scope="row"></td>
                                <td>{{_("Tel")}}:</td>
                                <td>{{order.customer_phone}}</td>
                            </tr>
                            <tr>
                                <td scope="row"></td>
                                <td>{{_("Email")}}:</td>
                                <td>{{order.customer_email}}</td>
                            </tr>
                            <tr>
                                <td scope="row"></td>
                                <td>{{_("Address")}}:</td>
                                <td>{{order.delivery_address}}</td>
                            </tr>
                        
                            
                    </table>
                    
                   
                </a>
            </div>
            <div class="list-group my-1">
               
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start disabled">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{_("Details du Produit")}}</h5>
                    </div>
                    <table class="table table-striped table-inverse table-responsive">
                        <thead class="thead-inverse">
                            <tr>
                                <th>{{_("Nom du Produit")}}</th>
                                <th> {{_("Prix Unitaire")}} </th>
                                <th>{{_("Quantité")}}</th>
                                <th>{{_("Frais de livraison")}}</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for product in order.products.all %}
                                <tr>
                                    <td>{{product.name}}</td>
                                    <td>{{product.promo_price}} {{_("CFA")}}</td>
                                    <td>{{order.orderproduct_set.first.quantity}} {{_("Pièce(s)")}}</td>
                                    <td>{{order.delivery_fee}} {{_("CFA")}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                    </table>
                </a>
            </div>
            <h5 class="float-right text-primary">Total : {{order.total_price}} CFA</h5>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="print-details" ><i class="fas fa-print    "></i></button>
         
        </div>
    </div>
</div>

<script>
    $("#print-details").click(function () {
        alert('print');
        screen.width/2;
        window.open("{% url 'sellerCenter:order.invoice' order.order_number %}", "", "top=0, left= 0");
    })
</script>

sellerCenter/templates/sellerCenter/order/invoice.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
   
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        body{
            /*background: url(/static/sellerCenter/img/logo.png); */
            background-size:100%;
            background-position: center;
            background-repeat: no-repeat;
            opacity: 0.9;
        }
    </style>
  </head>
  <body >
    <div class="container">
        <div class="ro">
            <strong class="float-left my-auto">{{order.updated_at}}</strong>
        </div>
        

        <div class=" row container">
            <h1 class="text-center container my-5">Kamer Business Center</h1>
            <!--<img src="{% static 'sellerCenter/img/logo.jpg' %}" height="40%" class="img-responsive ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" alt="Kamer Business center Official logo">-->
        </div>

        <div class=" row my-3">
            <div class="col-md-6">
                <h4><strong>Date: {{order.updated_at}}</strong></h4>
                <h4><strong>Statut commande: {{order.status}}</strong></h4>
                <h4><strong>Statut Paiement: {{order.payment_status}}</strong></h4>
            </div>
            <div class="col-md-6">
                <img src="{{order.barcode.url}}" height="150px" class="img-responsive ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" alt="Barcode">
            </div>
        </div>
         
        <div class="row container my-5">
            <div class="col-md-6">
                <h4>A:</h4>
                <h5><strong>{{order.customer_firstName}} {{order.customer_lastName}}</strong></h5>
                <h5>{{order.customer_phone}}</h5>
                <h5>{{order.customer_email}}</h5>
                <h5>{{order.delivery_address}}</h5>
            </div>
            <div class="col-md-6">
                <h4>De:</h4>
                <h4 >Kamer Business Center</h4>
                <h6 >+237 675648360</h6>
                <h6 >kamerbusinesscenter@gmail.com</h6>
                <h6 >{{_("Douala Borne 10 - Entrée Bienvenue")}}</h6>
            </div>
            
            
        </div>
        
    </div>
    <div class="container w-100">
        <table class="table table-striped table-inverse">
            <thead class="thead-inverse">
                <tr>
                   <th>{{_("Nom du Produit")}}</th>
                    <th> {{_("Prix Unitaire")}} </th>
                    <th>{{_("Quantité")}}</th>
                    <th>{{_("Frais de livraison")}}</th>
                    <th>{{_("Image du Produit")}}</th>
                </tr>
            </thead>
            <tbody>
                {% for product in order.products.all %}
                <tr>
                    <td>{{product.name}}</td>
                    <td>{{product.promo_price}} {{_("CFA")}}</td>
                    <td>{{order.orderproduct_set.first.quantity}} {{_("Pièce(s)")}}</td>
                    <td>{{order.delivery_fee}} {{_("CFA")}}</td>
                    <td> <img class="mx-auto img img-responsive" src = {{product.image.url}} height="100px"></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h5 class="float-right text-primary my-5">Total : {{order.total_price}} {{_("CFA")}}</h5>
    </div>
    <div class="container w-100">
        <div class="row container my-5">
            <div class="col-md-6">
                <h6>{{_("Date et signature Kamer Business Center")}}</h6>
            </div>
            <div class="col-md-6">
                <h6 class="float-right">{{_("Date et signature du client")}}</h6>
            </div>
        </div>
    </div>
    
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
        window.print()
    </script>
  </body>
</html>