kamerbusinesscenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
urlpatterns = [
    path('sellerCenter/',include('sellerCenter.urls')),
    path('shop/',include('shop.urls', namespace = 'shop')),
    path('admin/',admin.site.urls  ),
    path('',RedirectView.as_view(url='sellerCenter/' )),
    
]

sellerCenter/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from .forms import RegistrationForm

app_name = 'sellerCenter'

urlpatterns = [
   # path('', RedirectView.as_view(url='dashboard')),
    
    path('', RedirectView.as_view(url='dashboard')),
    path('dashboard', views.index, name = "dashboard"),
    path('users', views.users, name = "users"),
    path('products', views.products, name = "products"),
    path('orders', views.orders, name = "orders"),
    path('orders/export', views.export_orders, name = "orders.export"),
    path('login', auth_views.LoginView.as_view(), name = "login"),
    path('user', views.createUser, name = "user.create"),
    path('user/update/<int:user_id>', views.updateUser, name = "user.update"),
    path('user/form-update/<int:user_id>', views.form_updateUser, name = "user.form.update"),
    path('user/delete/<int:user_id>', views.deleteUser, name = "user.delete"),
    path('user/form-delete/<int:user_id>', views.form_deleteUser, name = "user.form.delete"),
    path('user/root/create', views.createsuperuser, name = "user.create.root"),
    path('product', views.createProduct, name = "product.create"),
    path('product/<str:sku>', views.createProduct, name = "product.view.shop"),
    path('product/update/<str:sku>', views.updateProduct, name = "product.update"),
    path('product/form-update/<str:sku>', views.form_updateProduct, name = "product.form.update"),
    path('product/delete/<str:sku>', views.deleteProduct, name = "product.delete"),
    path('product/form-delete/<str:sku>', views.form_deleteProduct, name = "product.form.delete"),
    path('seller/<str:sku>/referal', views.get_referal_link, name = "seller.product.referal"),

    path('order/<str:id>/details', views.detailsOrder, name = 'order.details'),
    path('order/<str:id>/invoice', views.generateInvoice, name ='order.invoice'),

    path('delivery_fees', views.deliveryFees, name = 'delivery_fees'),
    path('delivery_fee/create', views.createDeliveryFee, name = 'delivery_fee.create'),
    path('delivery_fee/<str:sku>/<str:city_id>', views.getDeliveryFee, name = 'delivery_fee.product.city'),
    
    path('cities', views.cities, name = 'cities'),
    path('city/create', views.createCity, name = 'city.create'),
]

shop/urls.py
from django.urls import path, include
from . import views
from django.views.generic import RedirectView

app_name = 'shop'

urlpatterns = [
   # path('', RedirectView.as_view(url='dashboard')),
    
    path('', RedirectView.as_view(url='dashboard')),
    path('product/<str:referal_id>', views.shop, name = "product.view.shop"),
    path('product/<str:referal_id>/order', views.makeOrder, name = "make.order"),
    path('thanks', views.thanks, name = "thanks"),

]

sellerCenter/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Product, DeliveryFee, City

class RegistrationForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username','email','last_name','first_name','password')
		#fields.widget.attrs.update({'class' : 'form-control'})

		widgets = { 
            'username': forms.TextInput(attrs={'class': 'form-control','id': 'username','placeholder': 'User Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control','id': 'inputEmail','placeholder': 'Email'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control','id': 'last_name','placeholder': 'Last Name'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control','id': 'first_name','placeholder': 'First Name'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control','id': 'password','placeholder': 'Password'}),
        }
class updateUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('email','last_name','first_name')
		#fields.widget.attrs.update({'class' : 'form-control'})

		widgets = { 
            'email': forms.EmailInput(attrs={'class': 'form-control','id': 'inputEmail','placeholder': 'Email'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control','id': 'last_name','placeholder': 'Last Name'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control','id': 'first_name','placeholder': 'First Name'}),
        }

class createProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ('name','description','promo_price','price','image')

		widgets = { 
            'name': forms.TextInput(attrs={'class': 'form-control','id': 'name','placeholder': 'Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'promo_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }
class updateProductForm(forms.ModelForm):
    image = forms.FileField(required = False, widget = forms.FileInput)
    class Meta:
        model = Product
        fields = ('name','description','promo_price','price','image')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','id': 'name','placeholder': 'Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'promo_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

class deliveryFeeForm(forms.ModelForm):
   
    class Meta:
        model = DeliveryFee
        fields = ('amount', 'sku', 'city')
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Amount'}),
            'sku': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
        }

class CreateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ('name', 'code')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Name'}),
            'code': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Code'}),
        }

sellerCenter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import RegistrationForm, updateUserForm, createProductForm, updateProductForm, deliveryFeeForm, CreateCityForm
from django.contrib import messages
from django.urls import reverse
from .models import Product, Order, ProductManagement, DeliveryFee, City, Referal
from .admin import OrderResource, ProductResource
#from .sku_generator import generate_sku


# Create your views here.
@login_required()
def index(request):
	labels = []
	data = []
	orders = Order.objects.all()
	products = Product.objects.all()
	users = User.objects.all()
	
	return render(request, 'sellerCenter/index.html',{'users': users, 'products':products, 'orders': orders})

@login_required()
def users(request):
	registration_form = RegistrationForm()
	users = User.objects.all()
	return render(request, 'sellerCenter/users.html', {'users': users})

@login_required()
def products(request):
	
	products = Product.objects.all().order_by('created_at')
	return render(request, 'sellerCenter/products.html', {'products':products})

@login_required()
def orders(request):
	orders = Order.objects.all().order_by('created_at')
	return render(request, 'sellerCenter/orders.html', {'orders': orders})

""" 
	Create, Update and delete User
"""

# Create a super user if not exist

def createsuperuser(request):
	reverse('sellerCenter:user.create.root')
	users = User.objects.all()
	if len(users) == 0:
		user = User.objects.create_superuser('admin', 'admin@kamerbusinesscenter.com', 'pass')
	return redirect('sellerCenter:dashboard')

@login_required()
def createUser(request):
	reverse('sellerCenter:user.create')
	if request.method == 'POST':
	
		registration_form = RegistrationForm(request.POST)
		users = User.objects.all()
		if registration_form.is_valid(): 
			user = User.objects.create_user(request.POST.get('username'), request.POST.get('email'), request.POST.get('password'))
			user.last_name = request.POST.get('last_name')
			user.first_name = request.POST.get('first_name')
			user.save()
			messages.success(request, 'User successful created !')
		else:
			messages.error(request, 'Invalid information, please check your form and correct some fields.')
		return render(request, 'sellerCenter/users.html', {'registration_form': registration_form,'users': users})
	
	else:
		registration_form = RegistrationForm()
		return render(request, 'sellerCenter/forms/user/register.html', {'registration_form': registration_form})
	#return render(request, 'sellerCenter/users.html')
	

@login_required()
def updateUser(request, user_id):
	reverse('sellerCenter:user.update', args=[user_id])
	form = updateUserForm()
	if user_id != None:
		user = get_object_or_404(User, pk=user_id)
		form = updateUserForm(request.POST, instance=user)

		if form.is_valid():
			form.save()
			messages.success(request, 'User successful updated !')
		else:
			messages.error(request, 'Invalid information, please check your form and correct some fields.')
	
	return redirect('sellerCenter:users')

@login_required()
def deleteUser(request, user_id):
	reverse('sellerCenter:user.delete', args=[user_id])
	if user_id != None:
		user = get_object_or_404(User, pk=user_id)
		user.delete()
		messages.success(request, 'User successful deleted !')
	return redirect('sellerCenter:users')

@login_required()
def form_updateUser(request, user_id):
	reverse('sellerCenter:user.form.update', args = [user_id])
	user = get_object_or_404(User, pk=user_id)
	form = updateUserForm(instance = user)
	return render(request, 'sellerCenter/forms/user/update.html', {'form': form, 'user_id':user.id})


@login_required()
def form_createUser(request, user_id):
	reverse('sellerCenter:user.form.create')
	registration_form = RegistrationForm()
	return render(request, 'sellerCenter/forms/user/register.html', {'registration_form': registration_form})

@login_required()
def form_deleteUser(request, user_id):
	reverse('sellerCenter:user.form.delete', args = [user_id])
	print(user_id)
	return render(request, 'sellerCenter/forms/user/delete.html', {'user_id': user_id})


""" 
	Product Management
"""
@login_required()
def createProduct(request, user_id=None):
	
	if request.method == 'POST':
		form_data = request.POST.copy()
		form = createProductForm(form_data, request.FILES)
		if form.is_valid():
			product = form.save(commit=False)
			product.set_id()
			product.save()
			ProductManagement.objects.create(user = request.user, product = product, action = "create")
			messages.success(request, 'Product Saved !')
		return redirect('sellerCenter:products')
	else:
		form = createProductForm()
		return render(request, 'sellerCenter/forms/product/create.html', {'form': form})

@login_required()
def updateProduct(request, sku):
	reverse('sellerCenter:product.update', args=[sku])
	product = get_object_or_404(Product, pk=sku)
	form = updateProductForm(request.POST, request.FILES, instance = product)
	if form.is_valid():
		product = form.save()
		ProductManagement.objects.create(user = request.user, product = product, action = "update")
		messages.success(request, 'Product updated !')
	return redirect('sellerCenter:products')

@login_required()
def deleteProduct(request, sku):
	reverse('sellerCenter:product.delete', args=[sku])
	product = get_object_or_404(Product, pk = sku)
	ProductManagement.objects.create(user = request.user, product = product, action = "delete")
	product.delete()
	messages.success(request, 'Product deleted !')
	return redirect('sellerCenter:products')

@login_required()
def form_updateProduct(request, sku):
	reverse('sellerCenter:product.form.update', args = [sku])
	product = get_object_or_404(Product, pk=sku)
	form = updateProductForm(instance = product)
	return render(request, 'sellerCenter/forms/product/update.html', {'form': form, 'product':product})


@login_required()
def form_createProduct(request, user_id):
	reverse('sellerCenter:product.form.create')
	registration_form = RegistrationForm()
	return render(request, 'sellerCenter/forms/product/create.html', {'registration_form': registration_form})

@login_required()
def form_deleteProduct(request, sku):
	reverse('sellerCenter:product.form.delete', args = [sku])
	return render(request, 'sellerCenter/forms/product/delete.html', {'sku': sku})

@login_required()
def detailsOrder(request, id):
	reverse('sellerCenter:order.details', args = [id])
	order = get_object_or_404(Order, pk = id)
	return render(request, 'sellerCenter/order/details.html', {'order': order })

@login_required()
def generateInvoice(request, id):
	reverse('sellerCenter:order.invoice', args = [id])
	order = get_object_or_404(Order, pk = id)
	return render(request, 'sellerCenter/order/invoice.html', {'order': order})


@login_required()
def deliveryFees(request):
	reverse('sellerCenter:delivery_fees')
	delivery_fees = DeliveryFee.objects.all()
	form = deliveryFeeForm()
	return render(request, 'sellerCenter/delivery_fee.html', {'delivery_fees' : delivery_fees, 'form': form})

@login_required()
def createDeliveryFee(request):
	if request.method == "POST":
		form = deliveryFeeForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Delivery Fee added !')
			return redirect('sellerCenter:delivery_fees')

@login_required()
def getDeliveryFee(request, sku, city_id):
	reverse('sellerCenter:delivery_fee.product.city', args = [sku, city_id])
	delivery_fee = DeliveryFee.objects.filter(sku=sku, city_id = city_id).first()
	return JsonResponse({'delivery_fee':delivery_fee.amount})

@login_required()
def updateDeliveryFee(request):
	reverse('sellerCenter:delivery_fee')
	delivery_fees = DeliveryFee.objects.all()
	return(request, 'sellerCenter/delivery_fee')

@login_required()
def cities(request):
	reverse('sellerCenter:cities')
	cities = City.objects.all().order_by('created_at')
	form = CreateCityForm()
	return render(request, 'sellerCenter/cities.html', {'cities':cities, 'form':form})

@login_required()
def createCity(request):
	reverse('sellerCenter:city.create')
	if request.method == 'POST':
		form = CreateCityForm(request.POST)
		if form.is_valid():
			city = form.save(commit = False)
			city.set_id()
			city.save()
			messages.success(request, 'City created !')
			return redirect('sellerCenter:cities')
		else:
			messages.error(request, 'Error in some field !')
			return redirect('sellerCenter:cities')

def export_orders(request, format = 'xls'):
    dataset = OrderResource().export()
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="orders.xls"'
    return response

@login_required()
def get_referal_link(request, sku):
	reverse('sellerCenter:seller.product.referal', args = [sku])
	# return the referal link for the product and the connected seller
	# and create a referal link if not yet set.
	referal = Referal.objects.filter(seller=request.user, product=sku).first()
	if referal == None:
		
		product = get_object_or_404(Product, pk = sku)
		referal = Referal.objects.create(seller = request.user, product = product)
		referal.set_id()
		referal.set_link()
		referal.save()

	return JsonResponse({'referal_link': referal.link})

sellerCenter/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="kamerbusinesscenter">
  <meta name="author" content="kamerbusinesscenter">

  <title>KBC Seller Center</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'sellerCenter/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static 'sellerCenter/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'sellerCenter/css/sb-admin.css' %}" rel="stylesheet">
  <script src="{% static 'sellerCenter/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'sellerCenter/vendor/chart.js/Chart.min.js' %}"></script>


</head>

<body id="page-top">
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message | safe }}
        </div>
    {% endfor %}
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="#">Kamer Business Center </a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>
    <img src="{% static 'sellerCenter/img/logo.jpg' %}" height="40px" class=".img-responsive ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" alt="kamerbusinesscenter logo">

    <!-- Navbar Search 
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    --> 

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-auto ">
    <!--
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      -->
      <!--
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      -->
      <li class="nav-item dropdown no-arrow ">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'sellerCenter:dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Seller Center</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sellerCenter:users' %}">
          <i class="fas fa-fw fa-users"></i>
          <span>Sellers</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sellerCenter:products' %}">
          <i class="fab fa-fw fa-product-hunt"></i>
          <span>Products</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sellerCenter:orders' %}">
          <i class="fas fa-fw fa-file-invoice-dollar"></i>
          <span>Orders</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sellerCenter:cities' %}">
          <i class="fas fa-fw fa-globe-africa"></i>
          <span>Cities</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sellerCenter:delivery_fees' %}">
          <i class="fas fa-fw fa-truck-loading"></i>
          <span>Delivery fee</span></a>
      </li>
    </ul>

    <div id="content-wrapper">
    {% block content %} {% endblock %}
      
      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto ">
          <div class="copyright text-center my-auto">
            <span>Copyright © Kamer Business Center 2020</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'sellerCenter/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'sellerCenter/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  
  <script src="{% static 'sellerCenter/vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'sellerCenter/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'sellerCenter/js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static 'sellerCenter/js/demo/datatables-demo.js' %}"></script>
  <script src="{% static 'sellerCenter/js/demo/chart-area-demo.js' %}"></script>

</body>

</html>